services:
  - type: web
    name: win-pro
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: DERIV_CLIENT_ID
        value: 34tb6qr80U6IIGqopktV4
      - key: SESSION_SECRET
        generateValue: true
